import Head from 'next/head';
import Container from '../components/Container';
import { useEffect,useState } from 'react';
import { Background } from '../components/Background';

export default function Home() {
  const [width,setWidth] = useState(null)
  const [dimension,setDimension] = useState({
    width:null,
    height:null
  })
  const [height,setHeight] = useState(null)  // const bodyRef = useCallback(node=>{
    //   if(node!==null){
    //     setWidth(node.clientWidth)
    //     // console.log(node.clientWidth)
    //   }
    // },[])

  useEffect(()=>{
    setDimension({width:window.innerWidth,height:window.innerHeight})
    window.addEventListener('resize',handleResize,false)
  },[])

  const handleResize = ()=>{
    setDimension({width:window.innerWidth,height:window.innerHeight})
    // console.log(window.innerWidth,window.innerHeight)
  }

  return (
    <div>
      <Head>
        <title>Akash Sharma | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Akash Sharma" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='relative'>
        <Background dimension = {dimension} />
        <Container />
      </main>
    </div>
  )
}
